# Generated by Django 2.1.8 on 2021-06-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LR_app', '0003_auto_20190923_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.CharField(max_length=45)),
                ('plan', models.TextField()),
                ('sDate', models.DateTimeField()),
                ('eDate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('uploadeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_travel', to='LR_app.User')),
                ('users_going', models.ManyToManyField(related_name='user_traveling', to='LR_app.User')),
            ],
        ),
    ]
